./bin/greedy -i data/graph_actors_dat.txt -n_apps 5 > resultMH/graph_actors_datRESULT.txt
./bin/greedy -i data/ego-facebook.txt -n_apps 5  > resultMH/ego-facebookRESULT.txt
./bin/greedy -i data/graph_CA-AstroPh.txt -n_apps 5  > resultMH/graph_CA-AstroPhRESULT.txt
./bin/greedy -i data/graph_CA-CondMat.txt -n_apps 5  > resultMH/graph_CA-CondMatRESULT.txt
./bin/greedy -i data/graph_CA-HepPh.txt -n_apps 5  > resultMH/graph_CA-HepPhRESULT.txt
./bin/greedy -i data/graph_football.txt -n_apps 5  > resultMH/graph_footballRESULT.txt
./bin/greedy -i data/graph_jazz.txt -n_apps 5  > resultMH/graph_jazzRESULT.txt
./bin/greedy -i data/socfb-Brandeis99.txt -n_apps 5  > resultMH/socfb-Brandeis99RESULT.txt
./bin/greedy -i data/socfb-Mich67.txt -n_apps 5  > resultMH/socfb-Mich67RESULT.txt
./bin/greedy -i data/soc-gplus.txt -n_apps 5  > resultMH/soc-gplusRESULT.txt
